export enum ERoutes {
   INDEX = "/",
   HOME = "/home",
   APURACAO_CBS = "/apuracao-cbs",
   APURACAO_CBS_DETALHE = "/apuracao-cbs/:id",
   APURACAO_IBS = "/apuracao-ibs",
   APURACAO_IS = "/apuracao-is",
   APURACAO_DERE = "/apuracao-dere",
   APURACAO_DERE_PLANO_REF = "/apuracao-dere/plano-ref",
   APURACAO_DERE_D1001 = "/apuracao-dere/d1001",
   APURACAO_DERE_D1011 = "/apuracao-dere/d1011",
   APURACAO_DERE_HISTORICO = "/apuracao-dere/historico",
   GESTAO_EVENTOS = "/gestao-eventos",
   PROCESSOS = "/processos",
   FINANCEIRO = "/financeiro",
   TRIBUTACAO_INTEGRAL = "/tributacao-integral",
   TRIBUTACAO_PERSONALIZADA = "/tributacao-personalizada",
   CONFIG_EMPRESAS = "/configuracoes/empresas",
}
