export enum ERoutes {
   INDEX = "/",
   HOME = "/home",
   APURACAO_CBS = "/apuracao-cbs",
   APURACAO_CBS_DETALHE = "/apuracao-cbs/:id",
   APURACAO_IBS = "/apuracao-ibs",
   APURACAO_IS = "/apuracao-is",
   APURACAO_DERE = "/apuracao-dere",
   APURACAO_DERE_PLANO_REF = "/apuracao-dere/plano-ref",
   APURACAO_DERE_D1001 = "/apuracao-dere/d1001",
   APURACAO_DERE_D1011 = "/apuracao-dere/d1011",
   APURACAO_DERE_HISTORICO = "/apuracao-dere/historico",
   GESTAO_EVENTOS = "/gestao-eventos",
   PROCESSOS = "/processos",
   FINANCEIRO = "/financeiro",
   TRIBUTACAO_INTEGRAL = "/tributacao-integral",
   TRIBUTACAO_PERSONALIZADA = "/tributacao-personalizada",
   CONFIG_EMPRESAS = "/configuracoes/empresas",
   CONFIG_ALIQUOTAS_CBS = "/configuracoes/aliquotas/cbs",
   CONFIG_ALIQUOTAS_IBS = "/configuracoes/aliquotas/ibs",
   CONFIG_ALIQUOTAS_IS = "/configuracoes/aliquotas/is",
   CONFIG_TABELAS_CLASSIFICACAO = "/configuracoes/tabelas/classificacao-tributaria",
   CONFIG_TABELAS_CREDITO_PRESUMIDO = "/configuracoes/tabelas/credito-presumido",
   CONFIG_TABELAS_ANEXOS = "/configuracoes/tabelas/anexos",
   CONFIG_TABELAS_INDICADORES = "/configuracoes/tabelas/indicadores-locais-operacao",
}
